### ISSUE TITLE
Navigating the Encase GUI 

### ISSUE THREAD

**Issue by FMS1989** [sdckey/EnScript-Samples#12]
Hello,

I hope this message finds you well! Is there a way for an Enscript to navigate through the GUI and bring up different views automatically in EnCase? For example, if I am within the home screen of my case in EnCase. I run the enscript by clicking on the drop down menu option at the top. I see the Enscript running in the bottom right hand corner.... But I have to manually click on "Evidence" under "Browse" ... Then I need to manually click on the "Console" tab to change from the  "Fields" tab to console window.

 I worked with SystemClass::ClearConsole(System Class::SHOWCONSOLE) before... But I don't want to clear the console... I just want it to automatically show it outside running the Enscript in the built in editor view

I was looking at the EvidenceClass and EvidenceOpenClass but nothing stood out. Do you know if there is a class in EnCase that controls the GUI? 

Appreciate any advice or suggestions you may have to point me in the right direction!

Thank you!

**Comment by sdckey** [comment]
The options for controlling the GUI are limited because many tasks in EnCase are event-driven. Some events will prompt the user to stop any active scripts before they can be handled. Some EnScripts may lock the current view.

There is a `SystemClass::KEEPCONSOLE` option that can be used in conjunction with `SystemClass::SHOWCONSOLE` to show the console without clearing it. That said, EnCase will usually only show the console once processing has been completed. Even then, the operation of this function is dependent on which pane(s) are active in the GUI. 

There is a class called **AutomationClass** that can be used to drive the GUI, but it's designed for QA purposes only; I do not recommend trying to use it for production scripts and cannot offer any documentation or examples.

In most cases, I find the easiest option is to advise the user of console output in the help documentation. Should there be some form of unrecoverable error, the user can view the backing-files in `%USERPROFILE%\Documents\EnCase\Logs`.

**Comment by FMS1989** [comment]
Thank you for taking the time to respond to my post! I appreciate your detailed response and thank you for the information.
