### ISSUE TITLE
task automation using enscript

### ISSUE THREAD

**Issue by nulld3v** [sdckey/EnScript-Samples#15]
Hi Simon,
I am currently trying to automate some fixed aspect of the tool which includes case creation and processing using EPManagerClass.

The issue is when I complete case creation part, it starts verifying the evidence which I do not require and need to stop this.
I am using below code to achieve the same:
ev.SetOpenMode(OPENEVIDENCEFILE);
ev.AddToCase(c, evopen);

and after this I write the case file which is completed but my next part which is processing on my specific enproc is not getting started. 

Do let me know if there is any other way to achieve the same.
Also, I have applied for developer about a week ago, still haven't got the access or any update regarding the same. Please help me get the documentation for enscript writing.

Do let me know if any other details required.

**Comment by nulld3v** [comment]
Hi Simon,

Thank you so much for your response.
Yes, this script helped me pretty much and it does what I am trying to achieve.
I am also trying to use specific hash library for hash analysis, is there a way to achieve the same when I am using EPManagerClass?

Also, I have submitted the form again with all the boxes ticked day before yesterday, still no luck with the same. Please suggest.

**Comment by nulld3v** [comment]
And also, I am looking for a way to emulate the attached evidence in my system, is there any way to achieve the same.

**Comment by sdckey** [comment]
> I am also trying to use specific hash library for hash analysis, is there a way to achieve the same when I am using EPManagerClass?

I don't believe so, not at present. EnCase is primarily a GUI-driven application, and from what I can see, the functionality needed to fully link a hash library to a case isn't exposed to EnScript.

I will ask for this functionality to be added, but I can't say if or when it will happen.

> Also, I have submitted the form again with all the boxes ticked day before yesterday, still no luck with the same. 

Sorry about that. Please email the relevant information to me at skey@opentext.com.

> And also, I am looking for a way to emulate the attached evidence in my system, is there any way to achieve the same.

Not that I am aware of. PDE and VFS are GUI-only features. I doubt that they would ever be exposed to EnScript due to the complexity involved.

You might, perhaps, consider streaming relevant data to an external application via a .NET assembly (the [YARA Scanner EnScript](https://security.opentext.com/appDetails/yara-scanner) does that), but you would need to work out the full details yourself - as per the FAQ, I can only provide generic code.
