### ISSUE TITLE
Select or tag entries with Enscript

### ISSUE THREAD

**Issue by wongkenny240** [sdckey/EnScript-Samples#3]
Hi Simon, 

Thank you for sharing your enscript examples.

I would like to ask two questions.
1. Is it possible to select or tag an entries in current view with enscript?
2. I try to export name of entries into a csv file with the code below, but when my enscript encounters some Chinese characters, the string is output to some unreadable text, is there any class that can help to format the string to readable format before output to the csv file? 

`logfile.WriteLine(Mastercounter + "," + entry.Name());`

Many thanks,
Kenny

**Comment by sdckey** [comment]
Tagging isn't possible in EnScript - it's a GUI-only function. It's possible to blue-check some items (bookmarks, for example) using an EnScript plugin, but the best option is probably to create a result-set. The user can tag the items contained therein after your script has finished processing.

EnCase uses Unicode by default, but the ability to display non-Roman/Latin characters in the output-file depends on the file's codepage and the presence of the byte-order marker (BOM). Be sure to open the output file using the FileClass::WRITETEXTCRLF option.

**Comment by wongkenny240** [comment]
Thanks Simon

I would like to ask two questions on looping through items. I try to iterate items with the script below to export tagged items, but the script pause
```
                for (ItemIteratorClass iter(c, PROMPT ,TAGGED); EntryClass e = iter.GetNextEntry();){
                       ProcessEntry(c, e, logfile, datestring);
                }
```
But if I change the script to below from iter(c, PROMPT ,TAGGED) to iter(c, NOPROXY, CURRENTVIEW_SELECTED), it works well

```
                for (ItemIteratorClass iter(c, NOPROXY, CURRENTVIEW_SELECTED); EntryClass e = iter.GetNextEntry();){
                       ProcessEntry(c, e, logfile, datestring);
                }
```
Do you know why the first one doesn't work?
And is it possible to iterate bookmarks directly and export the files from the bookmarks directly? 

Thank you.

Thanks,
Kenny

**Comment by sdckey** [comment]
> but the script pause

I'm not sure what you mean by this?

> And is it possible to iterate bookmarks directly and export the files from the bookmarks directly?

Yes, but you will need to use an instance of ItemCacheClass to obtain the bookmarked item or its file-data.

**Comment by wongkenny240** [comment]
For the first version ( `iter(c, PROMPT ,TAGGED) `) , the status bar show the script is running but the status bar didn't change for a long time. I have included 
`SystemClass::StatusMessage("Exporting: " + counter + " files" );` in order to keep track of how many files are exported, but the status bar only show my script's name and no file was exported.

But when I change the script, from `iter(c, PROMPT ,TAGGED)` to `iter(c, NOPROXY, CURRENTVIEW_SELECTED)`   (the only change I made in my script), the script can successfully export files and the status bar can reflect how many files are exported. 

Many thanks,
Kenny

**Comment by sdckey** [comment]
As a rule of thumb, it's your responsibility to update the status bar using `SystemClass::StatusInc()`.

That said, I rarely use the status-bar by itself with an iterator because one has to iterate twice: once to count the items to be iterated, and once again to process them. 

I tend to use a hybrid approach, i.e., I use the console to show each item being processed and the status bar to show the progress made with respect to the current item (when searching, for example).

Be warned that EnCase sometimes increments the status bar without being asked, when hashing for example.

Regarding the process of tagged items, I do this all the time as do many other EnScript developers. 

Some things to think about:

- Why are you only using `NOPROXY` with the `CURRENTVIEW_SELECTED` option? Why aren't you combining the two options with `TAGGED`, e.g. `NOPROXY | PROMPT`? It's rare to want to work with proxy objects as they're not linked-in to the entry tree; it also takes a little longer to compute calculated properties, which should have been calculated by evidence processing in any case.
- Have you tested the iteration loop without any other code using the console and/or debugger?
- Processing tagged items takes much longer because EnCase loads each item of evidence as it's needed to save memory.
- Iterating the same tagged items twice requires you to re-open the iterator using `ItemIteratorClass::Open()`. The list of tags (or result-set name) is stored in the iterator's `Name()` property and needs to be passed-in as the last parameter to the `Open()` method. 

It's difficult to know what's going wrong without seeing and debugging your code. I can't do that here - the EnScript forum on the EnCase Support Portal is the place for that.
