### ISSUE TITLE
ItemIteratorClass access passed docs

### ISSUE THREAD

**Issue by thiagotankian** [sdckey/EnScript-Samples#6]
Hi Simon! I’m using the ItemIteratorClass in order to navigate for each entry to look for a specific filename (that I know the name). The goal is that I’m trying to export the whole folder (where this file is located), but for that I had to create a new variable to iterate the evidence again (as I didn’t find a way to “iterate back” for the main folder when I found the file. Is there a better way to do that? Do you have some example with this similar situação (iterate back)? Kind regards!!

**Comment by sdckey** [comment]
Use `ItemIteratorClass::NOPROXY` as an option. You can then use the `Parent()` method inherited from `NodeClass` to retrieve the parent.

Don't try and hold-on to either item past the current iteration or you'll get an error.

**Comment by thiagotankian** [comment]
Thank you! I was able to get the parent folder but I was not able to export the whole folder due a closed file error.

When file is found ...
EntryFileClass.Open(EntryClass.Parent())
LocalFileClass.Open(EntryClass.Parent().FullPath(), FileClass::WRITE);
LocalFileClass.WriteNode(EntryFileClass); // I also tried WriteBuffer

Any idea what I am missing here?

Thanks again!

**Comment by sdckey** [comment]
There is no EnScript method for copying folders. It is not a trivial process because of a number of factors that include, but are not limited to:

- Possible path collisions due to recovered/deleted files.
- Path depth issues.
- The number of parent folders that should be copied.
- How to handle timestamps, alternate data streams, permissions, and file-system attributes taking into account the capabilities of the destination volume.
 
I shall shortly be posting an EnScript showing one possible approach, but it may not achieve everything you would like. Tasks such as this often involve some form of compromise.

**Comment by sdckey** [comment]
As promised:

- https://github.com/sdckey/EnScript-Samples/blob/master/18%20-%20File%20and%20Folder%20Extraction/Copy%20Folders%20Containing%20Matching%20File%20Names%20.EnScript
