### ISSUE TITLE
Enscript that searches by message id

### ISSUE THREAD

**Issue by LBL3327** [sdckey/EnScript-Samples#7]
Hello,

I am new to enscript and was wondering if you could provide some guidance on how to make a script that will look for a specific message ids of multiple emails from a pst loaded in encase? If you can provide any examples or point me in the right direction that be really appreciated!

**Comment by sdckey** [comment]
The code needed to iterate properties is used by the following script:

https://github.com/sdckey/EnScript-Samples/blob/master/13%20-%20Working%20With%20Record%20Properties/Extract%20Record-Fields%20to%20a%20Tab%20Delimited%20Spreadsheet.EnScript

That said, it's not necessary to use a script for this purpose: a condition can be used instead, one with a property-filter:

https://1drv.ms/u/s!AhvOQ0jE5HjHtjWrSOQSQ7_ExSPF?e=0gG59Y

**Comment by LBL3327** [comment]
Thank you! This is very helpful and points me in the right direction.

**Comment by FMS1989** [comment]
Hello,

Another quick question. Am I able to take some of the source code from the condition and turn it into an enscript?  I am trying to basically create an enscript that is similar to the condition, but I need to add some logging into it. This way it notifies me if it didn't find a specific message ID that I entered.  I am new to enscript and conditions so not sure if that is possible

Thanks!

**Comment by sdckey** [comment]
A condition is an EnScript filter that's written for you.

It has a Main() function that is applied to each item being filtered and returns a Boolean value. If Main() returns true, the item is shown otherwise it's hidden.

Accordingly, the Main() function in a condition/filter is called many times.

In a regular EnScript, the Main() function is only called once, and the script won't loop through any items unless you write the code needed to do that.

Accordingly, you can take a condition's code and paste it into a filter, but you can't turn a condition into a regular EnScript.

There is some scope for using the constructor/destructor in a condition/filter, but it's limited:

https://pastebin.com/Z6n68nX6

**Comment by FMS1989** [comment]
Thank you for the quick follow ups!

I found that you referenced the two documents below, so I am going to start to read them to get a better understanding. 

DFIR445-EnScript Fundamentals Version 8-01pi (03-01-2019).pdf
EnScript Language Reference Guide Version 1.1.pdf

I was checking out the condition and if I am understanding conditions correctly it basically just searches for what you specify (Ex. Message ID or .TXT extension) and if it finds the file it will appear within a table view in EnCase. Otherwise, it will just appear blank. So not much room to add extensive logic in conditions (like if you don't find this.. then do this). I noticed I couldn't edit the Source Code in EnCase. It just showed me what the Source Code was essentially which I am assuming gets created as you use the GUI to add different filters/searches you are looking for. 

Another example is I tried adding a message ID that I knew didn't exist and it just didn't return anything for the value within the table view. So I would have to then do an outside QC to check what emails don't exist within the mailbox that I have on my excel sheet to find. 

Am I on the right path of understanding conditions?

Forgive me for the long posts, but this is helpful since I am new to this language.

**Comment by sdckey** [comment]
Have a look at the following:
* https://github.com/sdckey/EnScript-Samples/tree/master/25%20-%20Hacking%20EnCase%20Conditions

**Comment by FMS1989** [comment]
Ah that seems to make more sense! Thank you for the detailed explanation! Also ty for the comments within the filters code. It was much easier for me to follow along and understand what was happening through out the code. I started reading the two documents you posted a link to which has been helping with understanding this language. So thank you!

**Comment by FMS1989** [comment]
Question for you! I load my pst and perform a view file structure in encase to see the individual folders and email files. Then I run my filter but I need to run it in "current view" selected in order to have the option to export out to MSG. I see that you used mainclass console.writeline for providing the results in the console. Does the console in encase use different classes so maybe I can switch it to write to the right console? If I click on "All Evidence" when running the filter it pops up the results tab with the writing in the console which I need for logging purposes. But now I need to export out to msg which it doesn't give me that option in that view. Any thoughts? My thought would be to somehow change the console view the filter writes to..... Not sure if that is the most efficient way though.... Is there a way to automatically export out to msg with the email files the script finds under responsive? Looking forward to your advice and input!

**Comment by sdckey** [comment]
You should be able to use the `RecordClass::ExportMessage()` function, so line-98 would become something like the following:

- https://pastebin.com/mEvCRmJQ

You would probably need a counter variable to avoid filename clashes. I wouldn't use the name of each message as it's not guaranteed to be Windows compatible.

**Comment by FMS1989** [comment]
Ok! I can look into that! Do you know how to get the console writing to appear when I run the filter as "current view"? If I click on "All Evidence Files" under filter it writes to the console, but it won't write if I click on "Current View" which is the view that allows me to export to msg by right clicking.
